export const goodsList = [
  {
    id:1,
    img:'https://cdn-we-retail.ym.tencent.com/tsr/goods/gh-1a.png',
    price:298,
    title:'简约餐盘耐热家用盘子菜盘套装多颜色简约餐盘耐热家用盘子',
    tag:'限时抢购',
    groupid:100011
  },
  {
    id:2,
    img:'https://hupc-blog-photo.oss-cn-beijing.aliyuncs.com/wp-content/uploads/2022/12/6f012a8ad2e64aa6d7fa8cc9cfdcf0.jpg',
    price:298,
    title:'精美礼品',
    tag:'2023春季爆款',
    groupid:100011
  },
  {
    id:3,
    img:'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-08b.png',
    price:298,
    title:'精美礼品',
    tag:'限时抢购',
    groupid:100011
  },
  {
    id:4,
    img:'ttps://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
    price:298,
    title:'简约餐盘耐热家用盘子菜盘套装多颜色简约餐盘耐热家用盘子',
    tag:'限时抢购',
    groupid:100012
  }
];